---
layout:     post  
title:      协程的进阶 
subtitle:   协程
date:       2019-10-10
author:     小卷子
header-img: img/tag-bg.jpg
catalog: true
tags:
    - 标签
---



### 协程进阶

~~~kotlin
public fun CoroutineScope.launch(
    context: CoroutineContext = EmptyCoroutineContext,
    start: CoroutineStart = CoroutineStart.DEFAULT,
    block: suspend CoroutineScope.() -> Unit
): Job {
    val newContext = newCoroutineContext(context)
    val coroutine = if (start.isLazy)
        LazyStandaloneCoroutine(newContext, block) else
        StandaloneCoroutine(newContext, active = true)
    coroutine.start(start, coroutine, block)
    return coroutine
}
~~~

以上代码是CoroutineScope的launch函数源码。

launch 的参数有三个，依次为协程上下文、协程启动模式、协程体。协程体自然不必多说 就是我们需要放到协程的代码。



~~~kotlin
        CoroutineScope(Dispatchers.Main).launch {
            logThead("当前线程是Main")
            getData()
            logThead("当前线程是Main")
        }

    private suspend fun getData() {

        withContext(Dispatchers.IO) {
            //doSomething
            logThead("IO")
        }
    }
~~~



### 协程上下文

**CoroutineContext**：协程上下文包含当前协程的信息。CoroutineContext很像一个类似list的数据结构。由一些协程配置的参数组成，包括协程的名字，协程运行的线程等。可以通过`+`组合这些参数。

协程上下文看起来是一个比较乱的东西，是一个很笼统的概念。调度器Dispatchers.Main就可以作为一个上下文，指定了这个协程运行在主线程。拦截器也可以作为上下文，拦截协程运行完后的回调。他们也可以组合在一起。

kotlin中 比较常用的Job、协程调度器(CoroutineDispatcher)、协程拦截器（ContinuationInterceptor）等都是CoroutineContext的子类，它们都是协程上下文

launch函数的上下文有默认参数是EmptyCoroutineContext，作用域里也会有上下文，会与传入的上下文相加，相加之后会变成一个CombinedContext。

```kotlin
    /**
     * Returns a context containing elements from this context and elements from  other [context].
     * The elements from this context with the same key as in the other one are dropped.
     */
    public operator fun plus(context: CoroutineContext): CoroutineContext =
        if (context === EmptyCoroutineContext) this else // fast path -- avoid lambda creation
            context.fold(this) { acc, element ->
                val removed = acc.minusKey(element.key)
                if (removed === EmptyCoroutineContext) element else {
                    // make sure interceptor is always last in the context (and thus is fast to get when present)
                    val interceptor = removed[ContinuationInterceptor]
                    if (interceptor == null) CombinedContext(removed, element) else {
                        val left = removed.minusKey(ContinuationInterceptor)
                        if (left === EmptyCoroutineContext) CombinedContext(element, interceptor) else
                            CombinedContext(CombinedContext(left, element), interceptor)
                    }
                }
            }

```

以上是plus函数的源码，它是一个`+	`的运算符重载函数。kotlin源码中大量使用了这个函数来进行上下文组合，所以大部分的CoroutineContext都是这个函数返回的CombinedContext。

协程上下文就和List一样都是一种数据结构，也有添加，删除元素等方法。

**协程上下文就是包含了协程的一些信息**



**调度器**

**Dispatchers**：调度器用来调度协程所运行的线程。

```kotlin
//部分源码
public abstract class CoroutineDispatcher :
    AbstractCoroutineContextElement(ContinuationInterceptor), ContinuationInterceptor {
    ...
    public abstract fun dispatch(context: CoroutineContext, block: Runnable)
    ...
}
```

调度器本身是协程上下文的子类，也是拦截器的子类。dispatch 方法会在拦截器的方法 interceptContinuation 中调用，进而实现协程的调度，进行线程切换等工作。

通常都会使用kotlin内置了一些调度器

**Dispatchers.Main**：主线程

**Dispatchers.IO**：线程池中取线层，子线程

**Dispatchers.Default**：线程池中取线层，子线程

**Dispatchers.Unconfined**：直接执行，不切换线程



**拦截器**

**ContinuationInterceptor**：拦截器，它也是一个上下文的实现方向（实现了CoroutineContext.Element）。拦截器可以左右协程的执行，为了保证拦截器的正确性协程上下文始终将拦截器放到最后（plus函数源码的最后）

```kotlin
    /**
     * Returns continuation that wraps the original [continuation], thus intercepting all resumptions.
     * This function is invoked by coroutines framework when needed and the resulting continuations are
     * cached internally per each instance of the original [continuation].
     *
     * This function may simply return original [continuation] if it does not want to intercept this particular continuation.
     *
     * When the original [continuation] completes, coroutine framework invokes [releaseInterceptedContinuation]
     * with the resulting continuation if it was intercepted, that is if `interceptContinuation` had previously
     * returned a different continuation instance.
     */
    public fun <T> interceptContinuation(continuation: Continuation<T>): Continuation<T>
```

ContinuationInterceptor的源码中有个interceptContinuation函数，参数需要一个Continuation。

协程的本质就是回调，回调就是Continuation，相当于CallBack

```kotlin
/**
 * Interface representing a continuation after a suspension point that returns a value of type `T`.
 */
@SinceKotlin("1.3")
public interface Continuation<in T> {
    /**
     * The context of the coroutine that corresponds to this continuation.
     */
    public val context: CoroutineContext

    /**
     * Resumes the execution of the corresponding coroutine passing a successful or failed [result] as the
     * return value of the last suspension point.
     */
    public fun resumeWith(result: Result<T>)
}

//以下是扩展函数

/**
 * Resumes the execution of the corresponding coroutine passing [value] as the return value of the last suspension point.
 */
@SinceKotlin("1.3")
@InlineOnly
public inline fun <T> Continuation<T>.resume(value: T): Unit =
    resumeWith(Result.success(value))

/**
 * Resumes the execution of the corresponding coroutine so that the [exception] is re-thrown right after the
 * last suspension point.
 */
@SinceKotlin("1.3")
@InlineOnly
public inline fun <T> Continuation<T>.resumeWithException(exception: Throwable): Unit =
    resumeWith(Result.failure(exception))
```

这里扩展方法中的resume就相当于回调中的onSucces()，resumeWithException相当于onFail()

协程通过拦截器拦截了回调，在拦截之后就可以做切线程等相关操作。



### 协程启动模式

```kotlin
/**
 * Defines start options for coroutines builders.
 * It is used in `start` parameter of [launch][CoroutineScope.launch], [async][CoroutineScope.async], and other coroutine builder functions.
 *
 * The summary of coroutine start options is:
 * * [DEFAULT] -- immediately schedules coroutine for execution according to its context;
 * * [LAZY] -- starts coroutine lazily, only when it is needed;
 * * [ATOMIC] -- atomically (in a non-cancellable way) schedules coroutine for execution according to its context;
 * * [UNDISPATCHED] -- immediately executes coroutine until its first suspension point _in the current thread_.
 */

--选自kotlin CoroutineStart源码的注释
```

这里可以看到有四种模式

DEFAULT，LAZY，ATOMIC，UNDISPATCHED

**DEFAULT**

立即开始协程体

**LAZY**

只有在需要的时候开始调协程 通过start，join，await等函数

**ATOMIC**

立即开始协程，在没有遇到挂起点之前不能被取消

**UNDISPATCHED**

立即在当前线程开始协程，直到遇到第一个挂起点后切换到指定的线程。相当于开始执行协程的时候不切换线程，遇到挂起点才切换



### 回调转换协程

~~~kotlin
    private suspend fun callBackAsCoroutine(succee: Boolean) =
        suspendCoroutine<Boolean> { continuation ->
            if (succee) {
                continuation.resume(succee)
            }else{
                continuation.resumeWithException(NullPointerException())
            }
        }
~~~

需要用到suspendCoroutine函数，如果执行成功调用`continuation.resume(succee)`失败调用` continuation.resumeWithException(NullPointerException())`在协程执行完成后会直接得到协程的结果，上例中是一个boolean的值



### 协程的异常处理

上面说过协程的resumeWithException函数就相当于回调的onFai。

协程的异常就相当于回调的onFail()，这里协程会抛出异常，如果不处理程序会crash。



协程可以直接用try的方式捕获异常

~~~kotlin
    private suspend fun exceptionTest() {

        try {
            callBackAsCoroutine(false)
        }catch ( e:Exception){
            log("协程异常")
        }
        
    }
~~~



**设置全局异常捕获**

协程也有全局异常处理的方式，在launch函数中传入`CoroutineExceptionHandler`来统一处理异常，这个`CoroutineExceptionHandler`也是协程上下文的一个实现。

~~~kotlin
    private suspend fun exceptionTest() {
        
        val executionHandler = CoroutineExceptionHandler { coroutineContext, throwable ->
            log("异常 ${throwable.message}")
        }
        
        coroutineScope.launch (executionHandler){

            callBackAsCoroutine(false)

        }
    }
~~~

这并不能算是全局的异常捕获，这个只是针对单个协程作用域的异常。

**使用async函数启动的协程只有在调用await的时候才会抛出异常**



**协程作用域中的异常**

```kotlin
        GlobalScope.launch(CoroutineExceptionHandler { coroutineContext, throwable ->
            log("父协程异常")
        }) {

            launch(CoroutineExceptionHandler { coroutineContext, throwable ->
                log("子协程异常")
            }) {
                callBackAsCoroutine(false)
            }
        }
```

通过` GlobalScope.launch`启动的协程，协程类的异常会向上传递。上例中的异常会传递到外面的父协程。如果父协程没有处理异常，子协程也无法捕获，程序最终会crash。



~~~kotlin
        GlobalScope.launch(CoroutineExceptionHandler { coroutineContext, throwable ->
            log("父协程异常")
        }) {
            supervisorScope {
                launch(CoroutineExceptionHandler { coroutineContext, throwable ->
                    log("子协程异常")
                }) {
                    callBackAsCoroutine(false)
                }
            }
        }
    }
~~~

在子协程创建前用supervisorScope定义作用域，此时子协程的异常将不会传递到父协程。但如果子协程并未捕获异常，异常最终将传递到父协程。

**CoroutineScope启动的协程和GlobalScope一样**，异常也是向上传递。如果不在内部定义supervisorScope，子协程将无法处理异常。

**一旦出现协程嵌套的情况，如果父协程没有处理异常，子协程就必须要使用`supervisorScope`来定义作用域，否则子协程将无法处理异常导致程序crash** 



### 协程的取消



协程的取消和线程的取消类似，都是使用一个变量记录协程的状态。

~~~kotlin
    private fun cancel(){        
        val job = coroutineScope.launch {

            log(1)
            delay(3000)
            log(2)
        }

        coroutineScope.launch {

            delay(1000)
            job.cancel()
        }
        
    }
~~~

这里启动的协程是否能在开启前就取消是无法保证的。有可能第一个log都无法输出就被取消，也有可能取消前整个协程都执行完了。











